import type { ResumeAnalysisResponse } from "@/types/analysis";

export const useAnalysisActions = (analysis: ResumeAnalysisResponse | null) => {
  const handleShare = () => {
    if (!analysis) return;
    const summary = `Resume Analysis Report\nScore: ${analysis.score}/100\nRecommendation: ${analysis.recommendation}\nSummary: ${analysis.extracted.summary}\n\nGenerated by Resume Analyzer AI`;
    navigator.clipboard.writeText(summary);
    alert("Analysis summary copied to clipboard! 📋");
  };

  const handleDownload = () => {
    if (!analysis) return;
    const dataStr =
      "data:text/json;charset=utf-8," +
      encodeURIComponent(JSON.stringify(analysis, null, 2));
    const downloadAnchorNode = document.createElement("a");
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute(
      "download",
      `resume_analysis_${Date.now()}.json`,
    );
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  return {
    handleShare,
    handleDownload,
  };
};
